spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=study;sslProtocol=TLSv1.2;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;autoReconnect=true;serverTimezone=Asia/Seoul;validationQuery=select 1
    username: sa
    password: Rainbowireles
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect